### ISSUE TITLE
Posebusters time split

### ISSUE THREAD

**Issue by bfabiandev** [PaddlePaddle/PaddleHelix#322]
Hi, 

In the technical report you state that "For training, we utilized targets from the Protein Data Bank (PDB) [8] released before September 30, 2021, along with self-distillation datasets.". Is that also true for the posebusters evaluation or did you train a model separately with Alphafold3's cutoff of September 30, **2019**? 

This is important since 130/428 structures in the original posebusters benchmark set were released before September 30, 2021 which would be significant test set leakage. 

Thanks, 
Beni

**Comment by xiaoyao4573** [comment]
There is indeed a data leakage issue in the evaluation on the PoseBusters dataset. We addressed this in our technical report, where we also presented the evaluation results after removing the leaked data. The average success rate decreases by 2%. Technical report: https://github.com/PaddlePaddle/PaddleHelix/blob/dev/apps/protein_folding/helixfold3/helixfold3_report.pdf

Thank you for your attention.

**Comment by bfabiandev** [comment]
Thanks for pointing that out, I didn't see that sentence. 

It's still not really a fair comparison as HelixFold3 was trained on 2 extra years of ligand data which might contain a bunch of near neighbours. If this ever gets published in a peer-reviewed setting, it would be nice to see a proper comparison on this benchmark with identical training cut-offs to make them truly comparable. 

Regardless, congrats on the rest of the results!
